import { IStackItemRepository } from '../../domain/repositories/stack-item.repository.interface.js';
import { CreateStackItemRequestDTO, StackItemDTO } from '../../../../../shared/src/stack.js';
import { StackItem } from '../../domain/entities/stack-item.entity.js';

export interface AddItemToStackInput {
  userId: string;
  data: CreateStackItemRequestDTO;
}

export class AddItemToStackUseCase {
  constructor(private stackRepo: IStackItemRepository) {}

  async execute(input: AddItemToStackInput): Promise<StackItemDTO> {
    const { userId, data } = input;

    const newItem: StackItem = {
      id: '', // Generated by Mongoose
      userId,
      supplementId: data.supplementId,
      dose: data.dose,
      frequency: data.frequency,
      timeOfDay: data.timeOfDay,
      notes: data.notes || null,
      createdAt: new Date(),
      updatedAt: new Date(),
      version: 0,
    };

    const savedItem = await this.stackRepo.save(newItem);
    
    return {
      id: savedItem.id,
      supplementId: savedItem.supplementId,
      dose: savedItem.dose,
      frequency: savedItem.frequency,
      timeOfDay: savedItem.timeOfDay,
      notes: savedItem.notes,
      version: savedItem.version,
      createdAt: savedItem.createdAt.toISOString(),
      updatedAt: savedItem.updatedAt.toISOString(),
    };
  }
}
export default AddItemToStackUseCase;
