import js from '@eslint/js';

import unusedImports from 'eslint-plugin-unused-imports';

export default [
  js.configs.recommended,
  {
    plugins: {
      'unused-imports': unusedImports,
    },
    files: ['src/**/*.js'],
    rules: {
      'no-unused-vars': 'off',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          varsIgnorePattern: '^_',
          args: 'after-used',
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-undef': 'error',
      'no-useless-assignment': 'off',
    },
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        confirm: 'readonly',
        location: 'readonly',
        navigator: 'readonly',
        WeakRef: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        Notification: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        Promise: 'readonly',
        Blob: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        File: 'readonly',
        prompt: 'readonly',
        performance: 'readonly',
        alert: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        indexedDB: 'readonly',
        IDBKeyRange: 'readonly',
        crypto: 'readonly',
        PopStateEvent: 'readonly',
        history: 'readonly',
        sessionStorage: 'readonly',
        AbortController: 'readonly',
        TextEncoder: 'readonly',
        screen: 'readonly',
        PerformanceObserver: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        Headers: 'readonly',
        logger: 'readonly',
        // Google Calendar SDK injected via <script> tag
        gapi: 'readonly',
        // Fetch API classes — available in browsers and Node 18+
        Response: 'readonly',
        AbortSignal: 'readonly',
        TextDecoder: 'readonly',
        // Vite replaces process.env at build time; declare readonly so linter doesn't error
        process: 'readonly',
        // CJS interop needed by one legacy file (notification-manager.js pending refactor)
        require: 'readonly',
      },
    },
  },
  {
    // Vitest globals for test files
    files: ['src/**/*.test.js'],
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        vi: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        global: 'readonly',
      },
    },
  },
];
