import { IUnitOfWork } from '../../../../shared/application/unit-of-work.interface.js';
import { IUserSettingsRepository } from '../../repositories/user-settings.repository.js';
import { IUserConsentRepository } from '../../repositories/user-consent.repository.js';
import { DocumentCatalogService } from '../../domain/document-catalog.service.js';
import { runWithRetry } from '../../../../shared/application/helpers/retry.js';

export interface GrantConsentInput {
  userId: string;
  consentType: 'privacy_policy' | 'terms_of_service' | 'marketing_emails';
  version: string;
  ipAddress: string;
  userAgent: string;
}

export class GrantConsentUseCase {
  constructor(
    private uow: IUnitOfWork,
    private settingsRepo: IUserSettingsRepository,
    private consentsRepo: IUserConsentRepository,
    private documentCatalog: DocumentCatalogService
  ) {}

  async execute(input: GrantConsentInput): Promise<void> {
    // 1. Backend is the source of truth for the hash catalogue
    const officialHash = this.documentCatalog.getHashForVersion(input.consentType, input.version);
    if (!officialHash) {
      throw new Error('ValidationError: Versão de documento inválida ou não suportada.');
    }

    await runWithRetry(async () => {
      await this.uow.runInTransaction(async () => {
        // 2. Persist the immutable audit log (Append-only)
        await this.consentsRepo.save({
          id: '', // Generated by Mongoose
          userId: input.userId,
          type: input.consentType,
          version: input.version,
          documentHash: officialHash,
          action: 'granted',
          ipAddress: input.ipAddress,
          userAgent: input.userAgent,
          timestamp: new Date()
        });

        // 3. Update the O(1) Read Model Snapshot with OCC
        const settings = await this.settingsRepo.findByUserId(input.userId);
        if (!settings) {
          throw new Error('EntityNotFoundError: Configurações do usuário não encontradas.');
        }

        // Convert snake_case consentType to camelCase consents field
        const consentKey = input.consentType.replace(/_([a-z])/g, g => g[1].toUpperCase()) as 'privacyPolicy' | 'termsOfService' | 'marketingEmails';
        settings.consents[consentKey] = true;

        await this.settingsRepo.save(settings);
      });
    });
  }
}
export default GrantConsentUseCase;
