export interface Checkin {
  userId: string;
  clientId: string;      // the local 'chk_...' ID generated by the browser
  supplementId: string;
  date: string;          // 'YYYY-MM-DD'
  timestamp: number;     // Unix ms
  note?: string;
  createdAt: Date;
}

export interface CheckinDTO {
  userId: string;
  clientId: string;
  supplementId: string;
  date: string;
  timestamp: number;
  note?: string;
  createdAt: string;
}

export interface BulkInsertResult {
  inserted: number;
  duplicates: number;
  total: number;
}

export class CheckinMapper {
  static toDTO(checkin: Checkin): CheckinDTO {
    return {
      userId: checkin.userId,
      clientId: checkin.clientId,
      supplementId: checkin.supplementId,
      date: checkin.date,
      timestamp: checkin.timestamp,
      note: checkin.note,
      createdAt: checkin.createdAt.toISOString(),
    };
  }
}
