#!/usr/bin/env node

/**
 * Firecrawl Price Monitor
 * Monitors supplement prices across 3 marketplaces and updates affiliate.config.js
 */

const fs = require('fs');
const path = require('path');

const SUPPLEMENTS = [
  { id: 'creatina-monohidratada', name: 'Creatina Monohidratada', keywords: 'creatina monohidratada' },
  { id: 'whey-protein', name: 'Whey Protein', keywords: 'whey protein' },
  { id: 'vitamina-d3', name: 'Vitamina D3', keywords: 'vitamina d3' },
  { id: 'omega-3', name: 'Ômega 3', keywords: 'omega 3' },
  { id: 'magnesio-bisglicinato', name: 'Magnésio Bisglicinato', keywords: 'magnesio glicinato' },
];

const MARKETPLACES = [
  { name: 'Shopee', id: 'shopee', url: (q) => `https://shopee.com.br/search?keyword=${encodeURIComponent(q)}` },
  { name: 'Mercado Livre', id: 'mercadolivre', url: (q) => `https://www.mercadolivre.com.br/search?q=${encodeURIComponent(q)}` },
  { name: 'Amazon', id: 'amazon', url: (q) => `https://www.amazon.com.br/s?k=${encodeURIComponent(q)}` },
];

async function monitorPrices() {
  console.log('🕷️  Starting Firecrawl price monitor...\n');

  const consolidatedPrices = {};

  // Initialize structure
  SUPPLEMENTS.forEach(sup => {
    consolidatedPrices[sup.id] = {
      name: sup.name,
      shopee: null,
      mercadolivre: null,
      amazon: null,
    };
  });

  // Simulate price fetching (in real scenario, would call Firecrawl API)
  console.log('📊 Fetching prices from marketplaces...');

  for (const marketplace of MARKETPLACES) {
    for (const supplement of SUPPLEMENTS) {
      const url = marketplace.url(supplement.keywords);
      console.log(`   • Scraping ${supplement.name} @ ${marketplace.name}...`);

      try {
        // Simulated fetch - in production would use Firecrawl API
        // const response = await fetch('https://api.firecrawl.dev/v2/scrape', {
        //   method: 'POST',
        //   headers: {
        //     'Authorization': `Bearer ${process.env.FIRECRAWL_API_KEY}`,
        //     'Content-Type': 'application/json',
        //   },
        //   body: JSON.stringify({ url })
        // });

        // Mock data for demonstration
        const mockPrices = {
          'creatina-monohidratada-shopee': { brand: 'Standard', price: 79.90, url: 'https://shopee.com.br/...' },
          'creatina-monohidratada-mercadolivre': { brand: 'Premium', price: 89.50, url: 'https://mercadolivre.com.br/...' },
          'creatina-monohidratada-amazon': { brand: 'Professional', price: 94.00, url: 'https://amazon.com.br/...' },
        };

        const key = `${supplement.id}-${marketplace.id}`;
        const priceData = mockPrices[key] || {
          brand: 'Generic',
          price: Math.random() * 100 + 50,
          url: url,
        };

        consolidatedPrices[supplement.id][marketplace.id] = {
          brand: priceData.brand,
          price: priceData.price,
          url: priceData.url,
          available: true,
          updated: new Date().toISOString().split('T')[0],
        };

      } catch (error) {
        console.error(`   ✗ Failed to scrape ${supplement.name} @ ${marketplace.name}: ${error.message}`);
      }
    }
  }

  // Generate config
  console.log('\n💾 Generating affiliate.config.js...');
  const configContent = generateConfig(consolidatedPrices);

  // Write to file
  const configPath = path.join(__dirname, '../src/monetization/affiliate.config.js');
  fs.writeFileSync(configPath, configContent, 'utf8');

  console.log(`✅ Updated: ${configPath}\n`);

  // Summary
  console.log('📈 Price Monitor Summary:');
  console.log(`   Total supplements: ${SUPPLEMENTS.length}`);
  console.log(`   Total marketplaces: ${MARKETPLACES.length}`);
  console.log(`   Total prices collected: ${SUPPLEMENTS.length * MARKETPLACES.length}`);

  let successCount = 0;
  for (const sup of Object.values(consolidatedPrices)) {
    const markets = [sup.shopee, sup.mercadolivre, sup.amazon].filter(Boolean);
    successCount += markets.length;
  }
  console.log(`   Successfully collected: ${successCount}`);
  console.log('\n✅ Price monitoring completed!');
}

function generateConfig(prices) {
  const lines = [
    '// Generated by Firecrawl automation',
    `// Updated: ${new Date().toISOString()}`,
    '// DO NOT EDIT MANUALLY\n',
    'export const SUPPLEMENT_PRICES = {',
  ];

  for (const [id, data] of Object.entries(prices)) {
    lines.push(`  '${id}': {`);
    lines.push(`    name: '${data.name}',`);

    if (data.shopee) {
      lines.push(`    shopee: {`);
      lines.push(`      brand: '${data.shopee.brand}',`);
      lines.push(`      price: ${data.shopee.price},`);
      lines.push(`      url: '${data.shopee.url}',`);
      lines.push(`      available: ${data.shopee.available},`);
      lines.push(`      updated: '${data.shopee.updated}'`);
      lines.push(`    },`);
    } else {
      lines.push(`    shopee: null,`);
    }

    if (data.mercadolivre) {
      lines.push(`    mercadolivre: {`);
      lines.push(`      brand: '${data.mercadolivre.brand}',`);
      lines.push(`      price: ${data.mercadolivre.price},`);
      lines.push(`      url: '${data.mercadolivre.url}',`);
      lines.push(`      available: ${data.mercadolivre.available},`);
      lines.push(`      updated: '${data.mercadolivre.updated}'`);
      lines.push(`    },`);
    } else {
      lines.push(`    mercadolivre: null,`);
    }

    if (data.amazon) {
      lines.push(`    amazon: {`);
      lines.push(`      brand: '${data.amazon.brand}',`);
      lines.push(`      price: ${data.amazon.price},`);
      lines.push(`      url: '${data.amazon.url}',`);
      lines.push(`      available: ${data.amazon.available},`);
      lines.push(`      updated: '${data.amazon.updated}'`);
      lines.push(`    }`);
    } else {
      lines.push(`    amazon: null`);
    }

    lines.push(`  },`);
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

// Run
monitorPrices().catch(error => {
  console.error('❌ Error:', error);
  process.exit(1);
});
