export interface CheckinDTO {
  id: string; // UUIDv4 generated by client
  supplementId: string;
  dose: number;
  checkedAt: string; // Device time (ISO 8601)
  syncedAt: string; // Server time (ISO 8601)
}

export interface LogCheckinRequestDTO {
  id: string; // Must match the UUIDv4 in the frontend
  supplementId: string;
  dose: number;
  checkedAt: string;
}

export interface GetCheckinHistoryRequestDTO {
  before?: string; // Cursor: ISO string of the checkedAt of the last seen item
  limit?: number; // Defaults to 20, max 50
}

export interface CheckinHistoryResponseDTO {
  items: CheckinDTO[];
  nextCursor: string | null;
  hasMore: boolean;
}
